version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
    - 27017:27017
    networks:
    - project-network
  project:
    image: project
    container_name: project
    ports:
    - 8080:8080
    environment:
      MONGO_DB_HOST: mongodb
      MONGO_DB_PORT: 27017
      MONGO_DB_DATABASE: projectdb
      CRYPTO_KEY: keyHML
    networks:
    - project-network
networks:
  project-network:
    driver: bridge